build:
	javac service/ATMManager.java
	javac service/Generator.java
	javac server/ATMManager.java
	javac server/ATMServer.java
	javac server/Generator.java
	javac client/ATMClient.java
	
clean:
	rm service/*.class
	rm server/*.class
	rm client/*.class
